language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-22
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

notifications:
  email:
    recipients:
     - ashokmylove@gmail.com
     - swayangjit029@gmail.com
    on_success: always
    on_failure: always

script: ./gradlew clean test aR
